#!/bin/sh

/usr/sbin/logrotate /etc/logrotate.d/pf9-kubelet /etc/logrotate.d/pf9-kube /etc/logrotate.d/pf9-nodeletd
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0
