// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/utils/container_runtime/utils.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// LoadImagesFromDir mocks base method.
func (m *MockRuntime) LoadImagesFromDir(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadImagesFromDir", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadImagesFromDir indicates an expected call of LoadImagesFromDir.
func (mr *MockRuntimeMockRecorder) LoadImagesFromDir(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadImagesFromDir", reflect.TypeOf((*MockRuntime)(nil).LoadImagesFromDir), arg0, arg1, arg2)
}

// LoadImagesFromFile mocks base method.
func (m *MockRuntime) LoadImagesFromFile(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadImagesFromFile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadImagesFromFile indicates an expected call of LoadImagesFromFile.
func (mr *MockRuntimeMockRecorder) LoadImagesFromFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadImagesFromFile", reflect.TypeOf((*MockRuntime)(nil).LoadImagesFromFile), arg0, arg1)
}
