// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/utils/container_runtime/container_runtime.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	containerd "github.com/containerd/containerd"
	gomock "github.com/golang/mock/gomock"
)

// MockContainerUtils is a mock of ContainerUtils interface.
type MockContainerUtils struct {
	ctrl     *gomock.Controller
	recorder *MockContainerUtilsMockRecorder
}

// MockContainerUtilsMockRecorder is the mock recorder for MockContainerUtils.
type MockContainerUtilsMockRecorder struct {
	mock *MockContainerUtils
}

// NewMockContainerUtils creates a new mock instance.
func NewMockContainerUtils(ctrl *gomock.Controller) *MockContainerUtils {
	mock := &MockContainerUtils{ctrl: ctrl}
	mock.recorder = &MockContainerUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerUtils) EXPECT() *MockContainerUtilsMockRecorder {
	return m.recorder
}

// CreateContainer mocks base method.
func (m *MockContainerUtils) CreateContainer(ctx context.Context, containerName, containerImage string) (containerd.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContainer", ctx, containerName, containerImage)
	ret0, _ := ret[0].(containerd.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockContainerUtilsMockRecorder) CreateContainer(ctx, containerName, containerImage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContainer", reflect.TypeOf((*MockContainerUtils)(nil).CreateContainer), ctx, containerName, containerImage)
}

// DestroyContainersInNamespace mocks base method.
func (m *MockContainerUtils) DestroyContainersInNamespace(ctx context.Context, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyContainersInNamespace", ctx, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyContainersInNamespace indicates an expected call of DestroyContainersInNamespace.
func (mr *MockContainerUtilsMockRecorder) DestroyContainersInNamespace(ctx, namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyContainersInNamespace", reflect.TypeOf((*MockContainerUtils)(nil).DestroyContainersInNamespace), ctx, namespace)
}

// DestroyContainersInNamespacesList mocks base method.
func (m *MockContainerUtils) DestroyContainersInNamespacesList(ctx context.Context, namespaces []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyContainersInNamespacesList", ctx, namespaces)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyContainersInNamespacesList indicates an expected call of DestroyContainersInNamespacesList.
func (mr *MockContainerUtilsMockRecorder) DestroyContainersInNamespacesList(ctx, namespaces interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyContainersInNamespacesList", reflect.TypeOf((*MockContainerUtils)(nil).DestroyContainersInNamespacesList), ctx, namespaces)
}

// EnsureContainerDestroyed mocks base method.
func (m *MockContainerUtils) EnsureContainerDestroyed(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureContainerDestroyed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureContainerDestroyed indicates an expected call of EnsureContainerDestroyed.
func (mr *MockContainerUtilsMockRecorder) EnsureContainerDestroyed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureContainerDestroyed", reflect.TypeOf((*MockContainerUtils)(nil).EnsureContainerDestroyed), arg0, arg1, arg2)
}

// EnsureContainerStoppedOrNonExistent mocks base method.
func (m *MockContainerUtils) EnsureContainerStoppedOrNonExistent(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureContainerStoppedOrNonExistent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureContainerStoppedOrNonExistent indicates an expected call of EnsureContainerStoppedOrNonExistent.
func (mr *MockContainerUtilsMockRecorder) EnsureContainerStoppedOrNonExistent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureContainerStoppedOrNonExistent", reflect.TypeOf((*MockContainerUtils)(nil).EnsureContainerStoppedOrNonExistent), arg0, arg1)
}

// EnsureContainersDestroyed mocks base method.
func (m *MockContainerUtils) EnsureContainersDestroyed(ctx context.Context, containers []containerd.Container, timeoutStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureContainersDestroyed", ctx, containers, timeoutStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureContainersDestroyed indicates an expected call of EnsureContainersDestroyed.
func (mr *MockContainerUtilsMockRecorder) EnsureContainersDestroyed(ctx, containers, timeoutStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureContainersDestroyed", reflect.TypeOf((*MockContainerUtils)(nil).EnsureContainersDestroyed), ctx, containers, timeoutStr)
}

// EnsureFreshContainerRunning mocks base method.
func (m *MockContainerUtils) EnsureFreshContainerRunning(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureFreshContainerRunning", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureFreshContainerRunning indicates an expected call of EnsureFreshContainerRunning.
func (mr *MockContainerUtilsMockRecorder) EnsureFreshContainerRunning(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureFreshContainerRunning", reflect.TypeOf((*MockContainerUtils)(nil).EnsureFreshContainerRunning), arg0, arg1, arg2)
}

// GetContainerWithGivenName mocks base method.
func (m *MockContainerUtils) GetContainerWithGivenName(ctx context.Context, containerName string) (containerd.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerWithGivenName", ctx, containerName)
	ret0, _ := ret[0].(containerd.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerWithGivenName indicates an expected call of GetContainerWithGivenName.
func (mr *MockContainerUtilsMockRecorder) GetContainerWithGivenName(ctx, containerName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerWithGivenName", reflect.TypeOf((*MockContainerUtils)(nil).GetContainerWithGivenName), ctx, containerName)
}

// GetContainersInNamespace mocks base method.
func (m *MockContainerUtils) GetContainersInNamespace(ctx context.Context, namespace string) ([]containerd.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainersInNamespace", ctx, namespace)
	ret0, _ := ret[0].([]containerd.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainersInNamespace indicates an expected call of GetContainersInNamespace.
func (mr *MockContainerUtilsMockRecorder) GetContainersInNamespace(ctx, namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainersInNamespace", reflect.TypeOf((*MockContainerUtils)(nil).GetContainersInNamespace), ctx, namespace)
}

// RemoveContainer mocks base method.
func (m *MockContainerUtils) RemoveContainer(ctx context.Context, container containerd.Container, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContainer", ctx, container, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContainer indicates an expected call of RemoveContainer.
func (mr *MockContainerUtilsMockRecorder) RemoveContainer(ctx, container, force interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainer", reflect.TypeOf((*MockContainerUtils)(nil).RemoveContainer), ctx, container, force)
}

// StopContainer mocks base method.
func (m *MockContainerUtils) StopContainer(ctx context.Context, container containerd.Container, timeoutStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainer", ctx, container, timeoutStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainer indicates an expected call of StopContainer.
func (mr *MockContainerUtilsMockRecorder) StopContainer(ctx, container, timeoutStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainer", reflect.TypeOf((*MockContainerUtils)(nil).StopContainer), ctx, container, timeoutStr)
}

// MockImageUtils is a mock of ImageUtils interface.
type MockImageUtils struct {
	ctrl     *gomock.Controller
	recorder *MockImageUtilsMockRecorder
}

// MockImageUtilsMockRecorder is the mock recorder for MockImageUtils.
type MockImageUtilsMockRecorder struct {
	mock *MockImageUtils
}

// NewMockImageUtils creates a new mock instance.
func NewMockImageUtils(ctrl *gomock.Controller) *MockImageUtils {
	mock := &MockImageUtils{ctrl: ctrl}
	mock.recorder = &MockImageUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageUtils) EXPECT() *MockImageUtilsMockRecorder {
	return m.recorder
}

// LoadImagesFromDir mocks base method.
func (m *MockImageUtils) LoadImagesFromDir(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadImagesFromDir", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadImagesFromDir indicates an expected call of LoadImagesFromDir.
func (mr *MockImageUtilsMockRecorder) LoadImagesFromDir(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadImagesFromDir", reflect.TypeOf((*MockImageUtils)(nil).LoadImagesFromDir), arg0, arg1, arg2)
}

// LoadImagesFromFile mocks base method.
func (m *MockImageUtils) LoadImagesFromFile(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadImagesFromFile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadImagesFromFile indicates an expected call of LoadImagesFromFile.
func (mr *MockImageUtilsMockRecorder) LoadImagesFromFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadImagesFromFile", reflect.TypeOf((*MockImageUtils)(nil).LoadImagesFromFile), arg0, arg1)
}
