apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: vol1
      mountPath: /vol1
  restartPolicy: Always
  volumes:
  - name: vol1
    emptyDir:
       medium: ""
