apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiproxy-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/proxy
  verbs:
  - proxy
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
