apiVersion: v1
kind: Config
users:
- name: system:kube-controller-manager
  user:
    client-certificate-data: __KUBE_CONTROLLER_MANAGER_CERT_BASE64__
    client-key-data: __KUBE_CONTROLLER_MANAGER_KEY_BASE64__
clusters:
- name: local
  cluster:
     server: https://__APISERVER_HOST__
     certificate-authority-data: __CA_CERT_BASE64__
contexts:
- context:
    cluster: local
    user: system:kube-controller-manager
  name: service-account-context
current-context: service-account-context
