name: release-rpm-and-deb

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Set up ruby
      uses: ruby/setup-ruby@v1.99.0
      with:
        ruby-version: 3.1 # 3.1.1 is latest as of writing ... no other reason

    - name: Set up fpm
      run: gem install fpm
      
    - name: Make
      env:
        TAG_NAME: ${{ env.GITHUB_REF_NAME }}
        BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
      run: make agent-rpm agent-deb --max-load=$(nproc)

  
    - name: Make nodeletctl
      env: 
        GOPRIVATE: github.com/platform9
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        cd nodeletctl
        git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
        go build .

    - name: Create tar file
      run: |
          cp build/pf9-kube/rpmbuild/RPMS/x86_64/pf9-kube-*.rpm* ./
          cp build/pf9-kube/pf9-kube-*.deb* ./
          tar -cvzf ./pf9-nodelet.tar.gz ./pf9-kube*.deb* ./pf9-kube-*.rpm*


    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/pf9-kube/rpmbuild/RPMS/x86_64/pf9-kube-*.rpm*
          build/pf9-kube/pf9-kube-*.deb*
          nodeletctl/nodeletctl
          pf9-nodelet.tar.gz
