
name: rpm-deb-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Set up ruby
      uses: ruby/setup-ruby@v1.99.0
      with:
        ruby-version: 3.1 # 3.1.1 is latest as of writing ... no other reason

    - name: Set up fpm
      run: gem install fpm
  
    - name: Make
      env:
        BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
      run: make agent-rpm agent-deb --max-load=$(nproc)
  
    - name: Make nodeletctl
      env: 
        GOPRIVATE: github.com/platform9
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        cd nodeletctl
        git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
        go build .

    - name: Create tar file
      run: |
          cp build/pf9-kube/rpmbuild/RPMS/x86_64/nodelet-*.rpm* ./
          cp build/pf9-kube/nodelet-*.deb* ./
          tar -cvzf ./pf9-nodelet.tar.gz ./nodelet-*.deb* ./nodelet-*.rpm*
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: all-artifacts
        path: |
          build/pf9-kube/rpmbuild/RPMS/x86_64/nodelet-*.rpm*
          build/pf9-kube/nodelet-*.deb*
          nodeletctl/nodeletctl
          pf9-nodelet.tar.gz
