apiVersion: v1
kind: Config
users:
- name: admin
  user:
    client-certificate-data: __ADMIN_CERT_BASE64__
    client-key-data: __ADMIN_KEY_BASE64__
clusters:
- name: local
  cluster:
     server: https://__APISERVER_HOST__
     certificate-authority-data: __CA_CERT_BASE64__
contexts:
- context:
    cluster: local
    user: admin
    namespace: default
  name: default-context
- context:
    cluster: local
    user: admin
    namespace: kube-system
  name: system-context
current-context: default-context
