apiVersion: v1
kind: Config
users:
- name: kubelet
  user:
    client-certificate-data: __KUBELET_CERT_BASE64__
    client-key-data: __KUBELET_KEY_BASE64__
clusters:
- name: local
  cluster:
     server: https://__APISERVER_HOST__
     certificate-authority-data: __CA_CERT_BASE64__
contexts:
- context:
    cluster: local
    user: kubelet
  name: service-account-context
current-context: service-account-context
